/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classes.DBConnection;
import Classes.Utilities;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Franco
 */
public class CrearRecurso extends javax.swing.JFrame {

    /**
     * Creates new form CrearUsuario
     */
    private Vector<Integer> idsTrabajadores;

    public CrearRecurso() {
        initComponents();
        setLocationRelativeTo(null);
        comboboxTipoActionPerformed(null);
        Utilities.getTrabajadoresWithComboBox(comboboxTrabajador,idsTrabajadores);
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboboxTrabajador = new javax.swing.JComboBox<>();
        textfieldNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        buttonCrearRecurso = new javax.swing.JButton();
        spinnerDisponibilidad = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        comboboxTipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crear Recurso");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Crear Recurso");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 11, -1, -1));

        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 112, -1, -1));

        comboboxTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxTrabajadorActionPerformed(evt);
            }
        });
        getContentPane().add(comboboxTrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 108, 160, -1));
        getContentPane().add(textfieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 109, 160, -1));

        jLabel3.setText("Datos del Recurso");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 43, -1, -1));

        buttonCrearRecurso.setText("Crear Recurso");
        buttonCrearRecurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCrearRecursoActionPerformed(evt);
            }
        });
        getContentPane().add(buttonCrearRecurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 177, -1, -1));

        spinnerDisponibilidad.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        getContentPane().add(spinnerDisponibilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 70, -1));

        jLabel9.setText("Disponibilidad (%)");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 143, -1, -1));

        comboboxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trabajador", "Recurso particular" }));
        comboboxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxTipoActionPerformed(evt);
            }
        });
        getContentPane().add(comboboxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 75, 170, -1));

        jLabel4.setText("Tipo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 79, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCrearRecursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCrearRecursoActionPerformed
        String sql = "INSERT INTO public.recurso(id_trabajador, nombre, disponibilidad) VALUES ( "
                + (((String) comboboxTipo.getSelectedItem()) == "Trabajador" ? idsTrabajadores.get(comboboxTrabajador.getSelectedIndex()) : null) + ",'"
                + (((String) comboboxTipo.getSelectedItem()) == "Trabajador" ? (String) comboboxTrabajador.getSelectedItem() : textfieldNombre.getText()) + "',"
                + spinnerDisponibilidad.getValue()+");";

        try {
            int result = DBConnection.executeQuery(sql);
            if (result == 1) {
                JOptionPane.showMessageDialog(this, "Recurso creado satisfactoriamente");
                dispose();
            }
        } catch (SQLException ex) {
            Logger.getLogger(CrearRecurso.class.getName()).log(Level.SEVERE, null, ex);
            Utilities.showErrorMessage(ex.getMessage());
        }
    }//GEN-LAST:event_buttonCrearRecursoActionPerformed

    private void comboboxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxTipoActionPerformed
        if (((String) comboboxTipo.getSelectedItem()) == "Trabajador") {
            comboboxTrabajador.setVisible(true);
            textfieldNombre.setVisible(false);
            spinnerDisponibilidad.setValue(1);
            spinnerDisponibilidad.setEnabled(false);
        } else {
            comboboxTrabajador.setVisible(false);
            textfieldNombre.setVisible(true);
            spinnerDisponibilidad.setEnabled(true);
        }
    }//GEN-LAST:event_comboboxTipoActionPerformed

    private void comboboxTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxTrabajadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxTrabajadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearRecurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearRecurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearRecurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearRecurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearRecurso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCrearRecurso;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboboxTipo;
    private javax.swing.JComboBox<String> comboboxTrabajador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner spinnerDisponibilidad;
    private javax.swing.JTextField textfieldNombre;
    // End of variables declaration//GEN-END:variables
}
