/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classes.DBConnection;
import Classes.Utilities;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.EventObject;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractCellEditor;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.SpinnerListModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.event.CellEditorListener;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableColumn;

/**
 *
 * @author Franco
 */
public class CrearTarea extends javax.swing.JFrame {

    /**
     * Creates new form CrearUsuario
     */
    private int id = -1;
    private int idProyecto;

    private Vector<Integer> idsTrabajadores = new Vector<>();
    private Vector<Integer> idsTareas = new Vector<>();
    private VentanaTareas ventanaTareas;

    private List<Integer> disponibilidadRecurso = new ArrayList<Integer>();

    public CrearTarea(VentanaTareas ventanaTareas, int idProyecto, Integer idTarea) {
        initComponents();
        setLocationRelativeTo(null);
        this.ventanaTareas = ventanaTareas;
        this.idProyecto = idProyecto;
        Utilities.getTareasWithList(listDependencias, idsTareas, idProyecto, idTarea);
        Utilities.getTareasWithComboBox(comboboxTareaAsociada, idsTareas, idProyecto, idTarea);
        comboboxTareaAsociada.addItem("Ninguna");
        comboboxTareaAsociada.setSelectedIndex(comboboxTareaAsociada.getItemCount() - 1);
        Utilities.getTrabajadoresWithComboBox(comboboxTrabajador, idsTrabajadores);
        Utilities.getRecursosWithTable(tablaRecursos);
        configureDisponibilidadCell();
        TableColumn col = tablaRecursos.getColumnModel().getColumn(tablaRecursos.getColumnCount() - 1);
        col.setCellEditor(new SpinnerEditor());

        listDependencias.setCellRenderer(new SelectedListCellRenderer());
    }

    public CrearTarea(VentanaTareas ventanaTareas, int idProyecto, Integer idTarea, ResultSet tarea, ResultSet tareasRequeridas, ResultSet recursosRequeridos) {
        this(ventanaTareas, idProyecto, idTarea);
        try {
            this.setTitle("Modificar Tarea");
            titulo.setText("Modificar Tarea");
            this.id = id;
            buttonCrearProyecto.setText("Modificar Tarea");
            textfieldNombre.setText(tarea.getString("nombre"));
            comboboxTrabajador.setSelectedItem(tarea.getString("nombreTrabajador"));
            spinnerDuracion.setValue(tarea.getInt("duracion_estimada"));
            textfieldFecha.setText(tarea.getString("fecha_inicio_prevista"));
            comboboxTareaAsociada.setSelectedItem(tarea.getString("tareaAsociada"));
        } catch (SQLException ex) {
            Logger.getLogger(CrearTarea.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void configureDisponibilidadCell() {
        for (int i = 0; i < tablaRecursos.getRowCount(); i++) {
            disponibilidadRecurso.add((Integer) tablaRecursos.getValueAt(i, tablaRecursos.getColumnCount() - 1));
            tablaRecursos.setValueAt(0, i, tablaRecursos.getColumnCount() - 1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        titulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboboxTareaAsociada = new javax.swing.JComboBox<String>();
        jLabel3 = new javax.swing.JLabel();
        buttonCrearProyecto = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        comboboxTrabajador = new javax.swing.JComboBox<String>();
        jLabel4 = new javax.swing.JLabel();
        textfieldNombre = new javax.swing.JTextField();
        spinnerDuracion = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textfieldFecha = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listDependencias = new javax.swing.JList<String>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaRecursos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crear Tarea");

        titulo.setText("Crear Tarea");

        jLabel2.setText("Responsable");

        jLabel3.setText("Datos del Tarea");

        buttonCrearProyecto.setText("Crear Tarea");
        buttonCrearProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCrearProyectoActionPerformed(evt);
            }
        });

        jLabel9.setText("Tarea Asociada");

        jLabel4.setText("Nombre");

        spinnerDuracion.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        jLabel10.setText("Duración (días)");

        jLabel5.setText("Fecha Inicio");

        textfieldFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/mm/yyyy"))));
        textfieldFecha.setText("23/12/2012");
        textfieldFecha.setToolTipText("dd/MM/yyyy");

        jLabel6.setText("Tareas requeridas");

        listDependencias.setToolTipText("Agrege haciendo click. Puede usar ctrl y shift");
        jScrollPane1.setViewportView(listDependencias);

        jLabel7.setText("Recursos requeridos");

        tablaRecursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaRecursos.setToolTipText("");
        tablaRecursos.setRowHeight(25);
        tablaRecursos.getTableHeader().setReorderingAllowed(false);
        tablaRecursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaRecursosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaRecursos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(titulo)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(jLabel9)
                                            .addGap(18, 18, 18)
                                            .addComponent(comboboxTareaAsociada, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel4)
                                                    .addGap(57, 57, 57)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(comboboxTrabajador, 0, 170, Short.MAX_VALUE)
                                                        .addComponent(textfieldNombre)
                                                        .addComponent(spinnerDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(textfieldFecha)))))
                                        .addGroup(layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(jLabel10))
                                        .addGroup(layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(jLabel5)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(411, 411, 411)
                        .addComponent(buttonCrearProyecto)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textfieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(comboboxTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(spinnerDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(textfieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboboxTareaAsociada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCrearProyecto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCrearProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCrearProyectoActionPerformed
        try {

            String sql, mensaje;

            if (id == -1) {
                sql = "INSERT INTO tarea(nombre, duracion_estimada, fecha_inicio_prevista, "
                        + "id_tarea_asociada, id_proyecto, id_trabajador, porcentaje_avance) VALUES ("
                        + "'" + textfieldNombre.getText() + "', "
                        + "" + (int) spinnerDuracion.getValue() + ", "
                        + "'" + textfieldFecha.getText() + "', "
                        + "" + (comboboxTareaAsociada.getSelectedIndex() == comboboxTareaAsociada.getItemCount() - 1 ? null : idsTareas.get(comboboxTareaAsociada.getSelectedIndex())) + ", "
                        + "" + idProyecto + ", "
                        + "" + idsTrabajadores.get(comboboxTrabajador.getSelectedIndex()) + ", "
                        + "0);";
                mensaje = "Tarea creada satisfactoriamente";
            } else {
                sql = "UPDATE public.proyecto SET cliente_asociado="
                        + idsTareas.get(comboboxTrabajador.getSelectedIndex()) + ", lider_proyecto = "
                        + idsTrabajadores.get(comboboxTareaAsociada.getSelectedIndex()) + ", nombre = '"
                        + textfieldNombre.getText() + "' WHERE id_proyecto = " + id + ";";
                mensaje = "Tarea modificada satisfactoriamente";
            }

            Integer id = DBConnection.executeQueryReturnID(sql);

            //dependecia de tareas
            for (int selectedIndice : listDependencias.getSelectedIndices()) {
                sql = "INSERT INTO tarea_dependencia(id_tarea, id_tarea_requerida) VALUES (" + id + ", " + idsTareas.get(selectedIndice) + ");";
                DBConnection.executeQuery(sql);
            }

            //dependencia de recursos
            for (int i = 0; i < tablaRecursos.getRowCount(); i++) {
                int cantidad = (int) tablaRecursos.getValueAt(i, tablaRecursos.getColumnCount() - 1);
                if (cantidad != 0) {
                    sql = "INSERT INTO tarea_recurso(id_tarea, id_recurso, cantidad_uso) VALUES (" + id + ", "
                            + tablaRecursos.getValueAt(i, 0) + ", " + cantidad + ");";
                    DBConnection.executeQuery(sql);

                    sql = "UPDATE recurso SET disponibilidad= " + (disponibilidadRecurso.get(i) - cantidad) + " WHERE id_recurso = " + tablaRecursos.getValueAt(i, 0) + ";";
                    DBConnection.executeQuery(sql);
                }
            }

            JOptionPane.showMessageDialog(this, mensaje);
            ventanaTareas.updateData();
            dispose();

        } catch (Exception ex) {
            Logger.getLogger(CrearTarea.class.getName()).log(Level.SEVERE, null, ex);
            Utilities.showErrorMessage(ex.getMessage());
        }
    }//GEN-LAST:event_buttonCrearProyectoActionPerformed

    private void tablaRecursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaRecursosMouseClicked
        System.out.println("valor " + tablaRecursos.getValueAt(tablaRecursos.getSelectedRow(), tablaRecursos.getColumnCount() - 1));
    }//GEN-LAST:event_tablaRecursosMouseClicked

    public class SelectedListCellRenderer extends DefaultListCellRenderer {

        @Override
        public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
            Component c = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
            if (isSelected) {
                c.setBackground(Color.GREEN);
            }
            return c;
        }
    }

    class SpinnerEditor extends AbstractCellEditor implements TableCellEditor {

        final JSpinner spinner = new JSpinner();

        public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected,
                int row, int column) {
            spinner.setModel(new SpinnerNumberModel((int) value, 0, (int) disponibilidadRecurso.get(row), 1));
            return spinner;
        }

        public boolean isCellEditable(EventObject evt) {

            return true;
        }

        public Object getCellEditorValue() {
            return spinner.getValue();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearTarea(null, 0, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCrearProyecto;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboboxTareaAsociada;
    private javax.swing.JComboBox<String> comboboxTrabajador;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listDependencias;
    private javax.swing.JSpinner spinnerDuracion;
    private javax.swing.JTable tablaRecursos;
    private javax.swing.JFormattedTextField textfieldFecha;
    private javax.swing.JTextField textfieldNombre;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
